name: video_player_android_mux
description: Android implementation of the video_player_mux plugin.
repository: https://github.com/hungryemon/video_player_android_mux # Repository Link
issue_tracker: https://github.com/hungryemon/video_player_android_mux/issues #Issues
version: 1.0.2


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: video_player_mux
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  #Uses video_player_platform_interface_mux
  video_player_platform_interface_mux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ## Pigeon is used for native bridging
  pigeon: 10.0.0
